/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hybridapp_MainActivity_FlexPopupInterface */

#ifndef _Included_com_example_hybridapp_MainActivity_FlexPopupInterface
#define _Included_com_example_hybridapp_MainActivity_FlexPopupInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
